using System;

namespace ICU4N.Util
{
    /// <summary>
    /// Exception thrown when the requested resource type 
    /// is not the same type as the available resource
    /// </summary>
    /// <author>ram</author>
    /// <stable>ICU 3.0</stable>
    public class UResourceTypeMismatchException : Exception
    {
        //// Generated by serialver from JDK 1.4.1_01
        //internal static readonly long serialVersionUID = 1286569061095434541L;

        /**
         * Constuct the exception with the given message
         * @param msg the error message for this exception
         * @stable ICU 3.0
         */
        public UResourceTypeMismatchException(string message)
            : base(message)
        {
        }
    }
}
