<Project>

  <!-- 
    ===========================================================================================================================================================
    This is a build warning for .NET SDK versions that are too old. .NET SDKs older than 9.0.200 fail to copy satellite assemblies
    with 3-character language codes to the build and/or publish output directory. It is required to be buildTransitive
    because there are many .NET SDKs that are broken in this way. If you customize the resources for your build, be sure to include this warning
    so users are prompted to install a .NET SDK that supports locales with 3-letter language codes. Note that these resources are optional and
    applications that do not require 3-letter language codes can do without them. This is the reason why it is a warning rather than an error.

    Supported Custom Properties

    ICU4NSuppressDotNetSDKVersionWarnings     -   Set to 'true' to opt out of build warnings for old .NET SDKs.
    ===========================================================================================================================================================
  -->

  <PropertyGroup Label="ICU4N properties">
    <_ICU4NDotNetSDKVersionMinimum>9.0.200</_ICU4NDotNetSDKVersionMinimum>

    <_ICU4NNormalizedDotNetSDKVersion Condition="'$(NETCoreSdkVersion)' != ''">$([System.String]::Copy('$(NETCoreSdkVersion)').Split('-')[0])</_ICU4NNormalizedDotNetSDKVersion>

    <!-- Support for the legacy ICU4NSuppressNuGetBuildTasksPackVersionWarnings property -->
    <ICU4NSuppressDotNetSDKVersionWarnings Condition="'$(ICU4NSuppressDotNetSDKVersionWarnings)' == '' and '$(ICU4NSuppressNuGetBuildTasksPackVersionWarnings)' != ''">$(ICU4NSuppressNuGetBuildTasksPackVersionWarnings)</ICU4NSuppressDotNetSDKVersionWarnings>
    <ICU4NSuppressDotNetSDKVersionWarnings Condition="'$(ICU4NSuppressDotNetSDKVersionWarnings)' == ''">false</ICU4NSuppressDotNetSDKVersionWarnings>
  </PropertyGroup>

  <Target Name="ICU4N_WarnIfDotNetSDKVersionDoesntSupport3LetterLanguageCodes"
    BeforeTargets="Build;Publish"
    Condition="'$(ICU4NSuppressDotNetSDKVersionWarnings)' != 'true'">

    <PropertyGroup>
      <_ICU4NDotNetSDKTooOld>false</_ICU4NDotNetSDKTooOld>
    </PropertyGroup>

    <PropertyGroup Condition="'$(_ICU4NNormalizedDotNetSDKVersion)' != ''">
      <_ICU4NDotNetSDKTooOld
        Condition="$([System.Version]::Parse('$(_ICU4NNormalizedDotNetSDKVersion)')) &lt; $([System.Version]::Parse('$(_ICU4NDotNetSDKVersionMinimum)'))">true</_ICU4NDotNetSDKTooOld>
    </PropertyGroup>

    <Warning
      Code="ICU4N_IDE_0001"
      Condition="'$(_ICU4NDotNetSDKTooOld)' == 'true'"
      Text=".NET SDK $(NETCoreSdkVersion) is older than $(_ICU4NDotNetSDKVersionMinimum) and does not support copying satellite assemblies with 3-character language codes to the build/publish output. ICU4N supports 3-letter language codes. Consider using .NET SDK $(_ICU4NDotNetSDKVersionMinimum) or later to build your project." />

  </Target>

</Project>
